[tasks.compile]
dependencies = [
	"compile-debug",
	"compile-release"
]

[tasks.compile-debug]
dependencies = [
	"cmake-debug",
	"ninja-debug",
	"copy-debug"
]

[tasks.compile-release]
dependencies = [
	"cmake-release",
	"ninja-release",
	"copy-release"
]

[tasks.cmake-clean]
script = '''
rm -rF ./build/debug/.cache
rm -rF ./build/debug/CMakeFiles
rm -rF ./build/debug/*.*
rm -rF ./build/release/.cache
rm -rF ./build/release/CMakeFiles
rm -rF ./build/release/*.*
'''
script_runner = "@shell"

[tasks.cmake-debug]
args = ["-S", ".", "-B", "./build/debug", "-G", "Ninja", "-DCMAKE_BUILD_TYPE:STRING=Debug"]
command = "cmake"

[tasks.cmake-release]
args = ["-S", ".", "-B", "./build/release", "-G", "Ninja", "-DCMAKE_BUILD_TYPE:STRING=Release"]
command = "cmake"

[tasks.copy-debug]
script = '''
cp -F build/debug/nodes.dll ../godot/libraries/nodes.win64d.dll # shell2batch: xcopy /f /r /y .\build\debug\nodes.dll ..\godot\libraries\nodes.win64d.dll*
'''
script_runner = "@shell"

[tasks.copy-release]
script = '''
cp -F build/release/nodes.dll ../godot/libraries/nodes.win64.dll # shell2batch: xcopy /f /r /y .\build\release\nodes.dll ..\godot\libraries\nodes.win64.dll*
'''
script_runner = "@shell"

[tasks.ninja-debug]
args = ["-C", "./build/debug"]
command = "ninja"

[tasks.ninja-release]
args = ["-C", "./build/release"]
command = "ninja"
