[application]

# dioxus project name
name = "dice-roller-godot-github-page"
# default platfrom
# you can also use `dioxus serve/build --platform XXX` to use other platform
# value: web | desktop
default_platform = "web"
# Web `build` & `serve` dist path
out_dir = "web"
# resource (static) file folder
asset_dir = "public"

[web.app]
# HTML title tag content
title = "Dice Roller (Godot)"

[web.watcher]
index_on_404 = true
watch_path = ["src"]

# include `assets` in web platform
[web.resource]
# CSS style file
style = ["assets/app.css"]
# Javascript code file
script = []

[web.resource.dev]
# Javascript code file
# serve: [dev-server] only
script = []

[application.plugins]
available = true
required = []
