name: Build GDExtension Project

on:
  push:
    branches: [ "main" ]
    paths:
      - "nodes/src/**.cc"
      - "nodes/src/**.hh"
      - "nodes/CMakeLists.txt"
  pull_request:
    branches: [ "main" ]
    paths:
      - "nodes/src/**.cc"
      - "nodes/src/**.hh"
      - "nodes/CMakeLists.txt"

concurrency:
  group: ${{github.workflow}}
  cancel-in-progress: false

jobs:
  build:
    strategy:
      matrix:
        config:
          - { name: "MacOS Clang", os: macos-latest, cc: "clang", cxx: "clang++", buildType: "Release" }
          - { name: "Linux gcc", os: ubuntu-latest, cc: "gcc", cxx: "g++", buildType: "Release" }
          - { name: "Windows Clang", os: windows-latest, cc: "clang", cxx: "clang++", buildType: "Release" }
    
    runs-on: ${{matrix.config.os}}
    
    steps:
    - uses: actions/checkout@v3
    
    # ---------- Set up the environment ----------
    - name: Linux Setup
      if: startsWith(matrix.config.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install cmake ninja-build
        cmake --version
        gcc --version
        ninja --version
    
    - name: MacOS Setup
      if: startsWith(matrix.config.os, 'macos')
      run: |
        brew install cmake ninja
        cmake --version
        clang++ --version
        ninja --version
    
    - name: Windows Setup
      if: startsWith(matrix.config.os, 'windows')
      run: |
        choco install cmake llvm ninja
        cmake --version
        clang++ --version
        ninja --version
    
    # ---------- Build the project ----------
    - name: Configure CMake
      env:
          CC: ${{matrix.config.cc}}
          CXX: ${{matrix.config.cxx}}
          BUILD_TYPE: ${{matrix.config.buildType}}
      run: cmake -S ${{github.workspace}}/nodes -B ${{github.workspace}}/nodes/build -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    
    - name: Build
      run: cmake --build ${{github.workspace}}/nodes/build
