name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        config:
          - { name: "MacOS Clang", os: macos-latest, cc: "clang", cxx: "clang++" }
          - { name: "Ubuntu gcc", os: ubuntu-latest, cc: "gcc", cxx: "g++" }
          - { name: "Windows Clang", os: windows-latest, cc: "clang", cxx: "clang++" }
    
    runs-on: ${{matrix.config.os}}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure CMake
      env:
          CC: ${{matrix.cc}}
          CXX: ${{matrix.cxx}}
          BUILD_TYPE: Release
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    
    - name: Build
      run: cmake --build ${{github.workspace}}/build
