name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        config:
          - { name: "Windows Clang", os: windows-latest, cc: "clang", cxx: "clang++" }
    
    runs-on: ${{matrix.config.os}}
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: UnsafePointer/cmake-clang-ninja-build-github-action@v1.4
      with:
        dir: "${{github.workspace}}/nodes"
